### ISSUE TITLE
[BUG] "Plant Growth" template (1SPL01_plants.xlsx) needs revision

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/Swate-templates#26]
The plant growth template needs an overall revision.
https://github.com/nfdi4plants/SWATE_templates/blob/main/templates/1SPL01_plants.xlsx

I just stumbled across some redundancies and attributes, that IMO did not really fit the description of "plant growth" at the very end: 

- Characteristic [plant structure] | PO:0009011 
- Parameter [project name] | NFDI4PSO:0002005 
- Parameter [sequencing method] | NFDI4PSO:0002006
- Parameter [investigation type] | NFDI4PSO:0002007
- Characteristic [environment (feature)] | NFDI4PSO:0002008
- Characteristic [plant-associated environmental package] | NFDI4PSO:0002010
- Characteristic [biome] | ENVO:00000428
- Characteristic [environment (material)] | NFDI4PSO:0002009

For instance, 

- `project name` could probably be the investigation identifier stored in isa.investigation.xlsx
- `investigation type` could likely be "study type" in isa.investigation.xlsx
- `sequencing method` really applies only to sequencing assays and could be handled in a different template

**Comment by omaus** [comment]
Agree.

But was `project name` and `investigation type` maybe for some conversion reasons? (i.e., endpoint repository-related fields)
If they are, we should at least comment it somewhere why we abolished them so that a person working at a converter sometime later knows about this and how to handle the related mapping.

**Comment by Brilator** [comment]
That's probably true for all of them. That's why I didn't just delete them. 
We need to work out rules how to curate templates here...

**Comment by xiaoranzhou** [comment]
Hi Dominik,

Those terms are "Mandatory" for ENA samples.
Redundency a friend of mine for data base, data transform, and data analysis.
Sometimes people ues it as index, sometiomes it is also called alias. 
Here is a short text for alias.
https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/upload-data-to-ena/slides-plain.html
The alias can make mapping and template-filling much easier.
I think the current template design also added some alias such as "Sample Name" and "Source Name"
Instead of setting rules of "which term goes to which template", I porpose to learn more from the endpoint repositories and make templates more dynamic and adaptive.

**Comment by xiaoranzhou** [comment]
> Hi Xiaroan, I do not fully understand, what you mean. To my understanding higher level metadata such as "project name" is stored on a different level in the ARC and not inside the annotation table an isa.study.xlsx or isa.assay.xlsx, for which we draft the templates.
> 
> > I think the current template design also added some alias such as "Sample Name" and "Source Name"
> 
> Source Name and Sample Name are ISA defaults.

Hi Dominik
Thank for the fast reply and the clarify the level definition of the ARC and also the ISA default attributes.
I think the first version of the different xlsx in the ARC is already really nice, but I also think there can be some exceptions or minimal duplications in the xlsx. On the one hand, some duplication is needed by some endpoint repositories, such as ENA. On the other hand, to have some duplication, which works as an alias (here https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/upload-data-to-ena/slides-plain.html) It can also make a connection of two templates easier. For example, by having a "project name", we can connection this template to a specific project, even if the template is in the wrong folder of other project. I wish it could be optional for some templates, just because it can avoid a lot of overhead and workload. 
A rule of thumb for the different layer of templates could be that, the higher level will not contain the lower level information, but the lower level could also contain the higher level information. For example, the assay can include some information from investigation, but the investigation will not go deep to the assays.

**Comment by Brilator** [comment]
> the higher level will not contain the lower level information, but the lower level could also contain the higher level information. For example, the assay can include some information from investigation, but the investigation will not go deep to the assays.

I understand the need, but this basically also is already covered. 
When creating isa.study.xlsx or isa.assay.xlsx workbooks using the ARC commander, it will add an extra investigation-style sheet for that information to the workbook

**Comment by Freymaurer** [comment]
What is the current state of this issue?

**Comment by Brilator** [comment]
@xiaoranzhou, does it break your ENA converter, if we delete all of the building blocks listed above? 

If so, I would kindly ask you to adapt the the converter in a way, that it retrieves the information from a different point in the ARC or specify an (additional) template for ENA converter, which could potentially cover only those missing terms to comply with ENA submission.

**Comment by xiaoranzhou** [comment]
Hi Dominik, thanks for asking. 
The converter development is aligned with BioHackathon Project 27 2023 "ISA submission to multiple repositories". The ENA template is no longer needed. Or at least the biohackathon project 27 has not reached this point yet. Here is a link to the repo[Project 27: Multi-Repository Data Submission using ISA-JSON](https://github.com/elixir-europe/biohackathon-projects-2023/tree/main/27). 

My own ENA template and converter are planned to be deprecated for two reasons: 1.No one is using them. 2. The 2023BH project 27 had more participation from the endpoint repositories and it seems to be very promising. 

There are two possibilities:
1. The BioHackathon project worked. ISA can be directly used for submission. The endpoint repositories check the ISA file and if some mandatory terms are missing, then we take this information and deliver it to the users.

2. We still need to develop our own converters. As the plant growth template is disentangled with ENA submission, the conversion between https://github.com/nfdi4plants/SWATE_templates/blob/main/templates/1SPL01_plants.xlsx and ENA submission for samples will not guarantee to work. If users want to submit to ENA, they need to use an ENA-specific template. I think this was what we agreed apon during the last discussion right?

If we all agree, then you can delete the redundant input.
