### ISSUE TITLE
[New template] Create GEO minimal templates

### ISSUE THREAD

**Issue by Martin-Kuhl** [nfdi4plants/Swate-templates#27]
**Is your feature request related to a problem? Please describe.**
As discussed yesterday, templates with the minimal required information by public repositories are desired.

**Describe the solution you'd like**
Templates for growth, extraction, the assay, and computation only with the minimal required information by GEO.

**Comment by Martin-Kuhl** [comment]
Was a bit quick in pushing to the main branch. Will open a pull request next time..

**Comment by Brilator** [comment]
## Growth_GEO_minimal.xlsx 
- the only GEO-mandatory attribute: organism
- the rest is rather generic and probably 
- Maybe the "organism" part could be covered with another very small template (currently called "plant_srouce.xlsx") 

## Extraction_GEO_minimal.xlsx
- Not sure, if `bio entity` is still "wanted"

## Computation_GEO_minimal.xlsx
- Could be cut down into 1. Data filtering and 2. Read Alignment. But makes sense to keep them, since required like that for GEO. 

## Assay_GEO_minimal.xlsx
- Could be cut down into 1. Library prep and 2. sequencing.
- Rationale: these are somewhat independent protocols. Some labs prepare their own libraries and submit them to a facility. So at that point they also get an ID (`Sample Name`), which the facility might pick up (`Source Name`).

**Comment by Martin-Kuhl** [comment]
GEO has a new template for submission.
## Growth
- Tissue, cell line, or cell type is required. Genotype and treatment are the remaining suggestions by them.

## Extraction
- bio entity corresponds to molecule, which is still in the template. We could think about replacing it with molecule, but I think this can also be handled by a converter.

## Assay
- Do you think the size of the template in its current state is acceptable? If yes, I would keep the template as one, as I have the impression that users are somehow "overwhelmed" by more templates and thereby, worksheets in Excel

**Comment by Brilator** [comment]
> Tissue, cell line, or cell type is required. Genotype and treatment are the remaining suggestions by them.
Ah, good to know. I didn't check the "mapping" sheet. 

> bio entity corresponds to molecule, which is still in the template. We could think about replacing it with molecule, but I think this can also be handled by a converter.
I'm just wondering if it's really used. If yes, it would be good to link it to a specific ontology and make selections easier. But this is somehow also linked to protocol type and technology type. 

> Do you think the size of the template in its current state is acceptable?
Yes 

> users are somehow "overwhelmed" by more templates and thereby, worksheets in Excel
Multiple templates could still be combined into one sheet. (e.g. plant source + plant growth + plant treatment, all with 3-4 building blocks)

**Comment by Martin-Kuhl** [comment]
> I'm just wondering if it's really used. If yes, it would be good to link it to a specific ontology and make selections easier. But this is somehow also linked to protocol type and technology type.

I think the field is mandatory, too. But you are right, as they have a controlled vocabulary for the child terms of molecule. Accordingly, this can be handled via our ontology

> Multiple templates could still be combined into one sheet. (e.g. plant source + plant growth + plant treatment, all with 3-4 building blocks)

Yes and no. Only one protocol type per Swate table is allowed. Splitting them would result in the need of two columns and just using one would result in the template as it currently is.

**Comment by Brilator** [comment]
ah, sorry, I forgot "molecule" comes from GEO. 

And true: multiple templates per sheet are not ideal..
